language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - pip install codecov
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("RigidBodyDynamics"); Pkg.test("RigidBodyDynamics"; coverage=true)'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "0.4" ]; then julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi

