site_name:        RigidBodyDynamics.jl
repo_url:         https://github.com/tkoolen/RigidBodyDynamics.jl/
site_description: RigidBodyDynamics.jl Documentation
site_author:      Twan Koolen

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - 'Home': 'index.md'
  - 'Quick start guide': 'quickstart.md'
  - 'Mechanism': 'mechanism.md'
  - 'Algorithms': 'algorithms.md'
  - 'Joints': 'joints.md'
  - 'Rigid bodies': 'rigidbody.md'
  - 'Spatial vector algebra': 'spatial.md'
